
lang_extensions_map = {
".bsl" : "1C Enterprise" ,
".os" : "1C Enterprise" ,
".2da" : "2-Dimensional Array" ,
".4dm" : "4D" ,
".abap" : "ABAP" ,
".asddls" : "ABAP CDS" ,
".abnf" : "ABNF" ,
".asc" : "AGS Script" ,
".ash" : "AGS Script" ,
".aidl" : "AIDL" ,
".al" : "AL" ,
".ampl" : "AMPL" ,
".mod" : "AMPL" ,
".g4" : "ANTLR" ,
".apib" : "API Blueprint" ,
".apl" : "APL" ,
".dyalog" : "APL" ,
".asl" : "ASL" ,
".dsl" : "ASL" ,
".asn" : "ASN.1" ,
".asn1" : "ASN.1" ,
".asax" : "ASP.NET" ,
".ascx" : "ASP.NET" ,
".ashx" : "ASP.NET" ,
".asmx" : "ASP.NET" ,
".aspx" : "ASP.NET" ,
".axd" : "ASP.NET" ,
".dats" : "ATS" ,
".hats" : "ATS" ,
".sats" : "ATS" ,
".as" : "ActionScript" ,
".adb" : "Ada" ,
".ada" : "Ada" ,
".ads" : "Ada" ,
".txt" : "Adblock Filter List" ,
".afm" : "Adobe Font Metrics" ,
".agda" : "Agda" ,
".als" : "Alloy" ,
".OutJob" : "Altium Designer" ,
".PcbDoc" : "Altium Designer" ,
".PrjPCB" : "Altium Designer" ,
".SchDoc" : "Altium Designer" ,
".as" : "AngelScript" ,
".angelscript" : "AngelScript" ,
".antlers.html" : "Antlers" ,
".antlers.php" : "Antlers" ,
".antlers.xml" : "Antlers" ,
".apacheconf" : "ApacheConf" ,
".vhost" : "ApacheConf" ,
".cls" : "Apex" ,
".trigger" : "Apex" ,
".agc" : "Apollo Guidance Computer" ,
".applescript" : "AppleScript" ,
".scpt" : "AppleScript" ,
".arc" : "Arc" ,
".asciidoc" : "AsciiDoc" ,
".adoc" : "AsciiDoc" ,
".asc" : "AsciiDoc" ,
".aj" : "AspectJ" ,
".asm" : "Assembly" ,
".a51" : "Assembly" ,
".i" : "Assembly" ,
".inc" : "Assembly" ,
".nas" : "Assembly" ,
".nasm" : "Assembly" ,
".astro" : "Astro" ,
".asy" : "Asymptote" ,
".aug" : "Augeas" ,
".ahk" : "AutoHotkey" ,
".ahkl" : "AutoHotkey" ,
".au3" : "AutoIt" ,
".avdl" : "Avro IDL" ,
".awk" : "Awk" ,
".auk" : "Awk" ,
".gawk" : "Awk" ,
".mawk" : "Awk" ,
".nawk" : "Awk" ,
".bas" : "BASIC" ,
".bal" : "Ballerina" ,
".bat" : "Batchfile" ,
".cmd" : "Batchfile" ,
".bf" : "Beef" ,
".befunge" : "Befunge" ,
".bf" : "Befunge" ,
".be" : "Berry" ,
".bib" : "BibTeX" ,
".bibtex" : "BibTeX" ,
".bicep" : "Bicep" ,
".bs" : "Bikeshed" ,
".bison" : "Bison" ,
".bb" : "BitBake" ,
".blade" : "Blade" ,
".blade.php" : "Blade" ,
".bb" : "BlitzBasic" ,
".decls" : "BlitzBasic" ,
".bmx" : "BlitzMax" ,
".bsv" : "Bluespec" ,
".bs" : "Bluespec BH" ,
".boo" : "Boo" ,
".bpl" : "Boogie" ,
".b" : "Brainfuck" ,
".bf" : "Brainfuck" ,
".bs" : "BrighterScript" ,
".brs" : "Brightscript" ,
".c" : "C" ,
".cats" : "C" ,
".h" : "C" ,
".idc" : "C" ,
".cs" : "C#" ,
".cake" : "C#" ,
".csx" : "C#" ,
".linq" : "C#" ,
".cpp" : "C++" ,
".c++" : "C++" ,
".cc" : "C++" ,
".cp" : "C++" ,
".cppm" : "C++" ,
".cxx" : "C++" ,
".h" : "C++" ,
".h++" : "C++" ,
".hh" : "C++" ,
".hpp" : "C++" ,
".hxx" : "C++" ,
".inc" : "C++" ,
".inl" : "C++" ,
".ino" : "C++" ,
".ipp" : "C++" ,
".ixx" : "C++" ,
".re" : "C++" ,
".tcc" : "C++" ,
".tpp" : "C++" ,
".txx" : "C++" ,
".c-objdump" : "C-ObjDump" ,
".chs" : "C2hs Haskell" ,
".cds" : "CAP CDS" ,
".cil" : "CIL" ,
".clp" : "CLIPS" ,
".cmake" : "CMake" ,
".cmake.in" : "CMake" ,
".cob" : "COBOL" ,
".cbl" : "COBOL" ,
".ccp" : "COBOL" ,
".cobol" : "COBOL" ,
".cpy" : "COBOL" ,
".dae" : "COLLADA" ,
".cson" : "CSON" ,
".css" : "CSS" ,
".csv" : "CSV" ,
".cue" : "CUE" ,
".w" : "CWeb" ,
".cabal" : "Cabal Config" ,
".cdc" : "Cadence" ,
".cairo" : "Cairo" ,
".mligo" : "CameLIGO" ,
".capnp" : "Cap'n Proto" ,
".mss" : "CartoCSS" ,
".ceylon" : "Ceylon" ,
".chpl" : "Chapel" ,
".ch" : "Charity" ,
".crc32" : "Checksums" ,
".md2" : "Checksums" ,
".md4" : "Checksums" ,
".md5" : "Checksums" ,
".sha1" : "Checksums" ,
".sha2" : "Checksums" ,
".sha224" : "Checksums" ,
".sha256" : "Checksums" ,
".sha256sum" : "Checksums" ,
".sha3" : "Checksums" ,
".sha384" : "Checksums" ,
".sha512" : "Checksums" ,
".ck" : "ChucK" ,
".circom" : "Circom" ,
".cirru" : "Cirru" ,
".clw" : "Clarion" ,
".clar" : "Clarity" ,
".asp" : "Classic ASP" ,
".icl" : "Clean" ,
".dcl" : "Clean" ,
".click" : "Click" ,
".clj" : "Clojure" ,
".bb" : "Clojure" ,
".boot" : "Clojure" ,
".cl2" : "Clojure" ,
".cljc" : "Clojure" ,
".cljs" : "Clojure" ,
".cljs.hl" : "Clojure" ,
".cljscm" : "Clojure" ,
".cljx" : "Clojure" ,
".hic" : "Clojure" ,
".soy" : "Closure Templates" ,
".conllu" : "CoNLL-U" ,
".conll" : "CoNLL-U" ,
".ql" : "CodeQL" ,
".qll" : "CodeQL" ,
".coffee" : "CoffeeScript" ,
"._coffee" : "CoffeeScript" ,
".cake" : "CoffeeScript" ,
".cjsx" : "CoffeeScript" ,
".iced" : "CoffeeScript" ,
".cfm" : "ColdFusion" ,
".cfml" : "ColdFusion" ,
".cfc" : "ColdFusion CFC" ,
".lisp" : "Common Lisp" ,
".asd" : "Common Lisp" ,
".cl" : "Common Lisp" ,
".l" : "Common Lisp" ,
".lsp" : "Common Lisp" ,
".ny" : "Common Lisp" ,
".podsl" : "Common Lisp" ,
".sexp" : "Common Lisp" ,
".cwl" : "Common Workflow Language" ,
".cp" : "Component Pascal" ,
".cps" : "Component Pascal" ,
".cl" : "Cool" ,
".coq" : "Coq" ,
".v" : "Coq" ,
".cppobjdump" : "Cpp-ObjDump" ,
".c++-objdump" : "Cpp-ObjDump" ,
".c++objdump" : "Cpp-ObjDump" ,
".cpp-objdump" : "Cpp-ObjDump" ,
".cxx-objdump" : "Cpp-ObjDump" ,
".creole" : "Creole" ,
".cr" : "Crystal" ,
".orc" : "Csound" ,
".udo" : "Csound" ,
".csd" : "Csound Document" ,
".sco" : "Csound Score" ,
".cu" : "Cuda" ,
".cuh" : "Cuda" ,
".cue" : "Cue Sheet" ,
".curry" : "Curry" ,
".cy" : "Cycript" ,
".cyp" : "Cypher" ,
".cypher" : "Cypher" ,
".pyx" : "Cython" ,
".pxd" : "Cython" ,
".pxi" : "Cython" ,
".d" : "D" ,
".di" : "D" ,
".d-objdump" : "D-ObjDump" ,
".d2" : "D2" ,
".com" : "DIGITAL Command Language" ,
".dm" : "DM" ,
".zone" : "DNS Zone" ,
".arpa" : "DNS Zone" ,
".d" : "DTrace" ,
".dfy" : "Dafny" ,
".darcspatch" : "Darcs Patch" ,
".dpatch" : "Darcs Patch" ,
".dart" : "Dart" ,
".dwl" : "DataWeave" ,
".dsc" : "Debian Package Control File" ,
".dsc" : "DenizenScript" ,
".dhall" : "Dhall" ,
".diff" : "Diff" ,
".patch" : "Diff" ,
".x" : "DirectX 3D File" ,
".dockerfile" : "Dockerfile" ,
".djs" : "Dogescript" ,
".env" : "Dotenv" ,
".dylan" : "Dylan" ,
".dyl" : "Dylan" ,
".intr" : "Dylan" ,
".lid" : "Dylan" ,
".e" : "E" ,
".eml" : "E-mail" ,
".mbox" : "E-mail" ,
".ebnf" : "EBNF" ,
".ecl" : "ECL" ,
".eclxml" : "ECL" ,
".ecl" : "ECLiPSe" ,
".ejs" : "EJS" ,
".ect" : "EJS" ,
".ejs.t" : "EJS" ,
".jst" : "EJS" ,
".eq" : "EQ" ,
".sch" : "Eagle" ,
".brd" : "Eagle" ,
".eb" : "Easybuild" ,
".epj" : "Ecere Projects" ,
".html" : "Ecmarkup" ,
".edgeql" : "EdgeQL" ,
".esdl" : "EdgeQL" ,
".editorconfig" : "EditorConfig" ,
".edc" : "Edje Data Collection" ,
".e" : "Eiffel" ,
".ex" : "Elixir" ,
".exs" : "Elixir" ,
".elm" : "Elm" ,
".elv" : "Elvish" ,
".el" : "Emacs Lisp" ,
".emacs" : "Emacs Lisp" ,
".emacs.desktop" : "Emacs Lisp" ,
".em" : "EmberScript" ,
".emberscript" : "EmberScript" ,
".erl" : "Erlang" ,
".app" : "Erlang" ,
".app.src" : "Erlang" ,
".es" : "Erlang" ,
".escript" : "Erlang" ,
".hrl" : "Erlang" ,
".xrl" : "Erlang" ,
".yrl" : "Erlang" ,
".e" : "Euphoria" ,
".ex" : "Euphoria" ,
".fs" : "F#" ,
".fsi" : "F#" ,
".fsx" : "F#" ,
".fst" : "F*" ,
".fsti" : "F*" ,
".flf" : "FIGlet Font" ,
".fx" : "FLUX" ,
".flux" : "FLUX" ,
".factor" : "Factor" ,
".fy" : "Fancy" ,
".fancypack" : "Fancy" ,
".fan" : "Fantom" ,
".dsp" : "Faust" ,
".fnl" : "Fennel" ,
".f" : "Filebench WML" ,
".fs" : "Filterscript" ,
".ftl" : "Fluent" ,
".for" : "Formatted" ,
".eam.fs" : "Formatted" ,
".fth" : "Forth" ,
".4th" : "Forth" ,
".f" : "Forth" ,
".for" : "Forth" ,
".forth" : "Forth" ,
".fr" : "Forth" ,
".frt" : "Forth" ,
".fs" : "Forth" ,
".f" : "Fortran" ,
".f77" : "Fortran" ,
".for" : "Fortran" ,
".fpp" : "Fortran" ,
".f90" : "Fortran Free Form" ,
".f03" : "Fortran Free Form" ,
".f08" : "Fortran Free Form" ,
".f95" : "Fortran Free Form" ,
".bi" : "FreeBasic" ,
".bas" : "FreeBasic" ,
".ftl" : "FreeMarker" ,
".fr" : "Frege" ,
".fut" : "Futhark" ,
".g" : "G-code" ,
".cnc" : "G-code" ,
".gco" : "G-code" ,
".gcode" : "G-code" ,
".gaml" : "GAML" ,
".gms" : "GAMS" ,
".g" : "GAP" ,
".gap" : "GAP" ,
".gd" : "GAP" ,
".gi" : "GAP" ,
".tst" : "GAP" ,
".md" : "GCC Machine Description" ,
".gdb" : "GDB" ,
".gdbinit" : "GDB" ,
".gd" : "GDScript" ,
".ged" : "GEDCOM" ,
".glsl" : "GLSL" ,
".fp" : "GLSL" ,
".frag" : "GLSL" ,
".frg" : "GLSL" ,
".fs" : "GLSL" ,
".fsh" : "GLSL" ,
".fshader" : "GLSL" ,
".geo" : "GLSL" ,
".geom" : "GLSL" ,
".glslf" : "GLSL" ,
".glslv" : "GLSL" ,
".gs" : "GLSL" ,
".gshader" : "GLSL" ,
".rchit" : "GLSL" ,
".rmiss" : "GLSL" ,
".shader" : "GLSL" ,
".tesc" : "GLSL" ,
".tese" : "GLSL" ,
".vert" : "GLSL" ,
".vrx" : "GLSL" ,
".vs" : "GLSL" ,
".vsh" : "GLSL" ,
".vshader" : "GLSL" ,
".gn" : "GN" ,
".gni" : "GN" ,
".gsc" : "GSC" ,
".csc" : "GSC" ,
".gsh" : "GSC" ,
".gml" : "Game Maker Language" ,
".gmi" : "Gemini" ,
".4gl" : "Genero 4gl" ,
".per" : "Genero per" ,
".gs" : "Genie" ,
".kid" : "Genshi" ,
".ebuild" : "Gentoo Ebuild" ,
".eclass" : "Gentoo Eclass" ,
".gbr" : "Gerber Image" ,
".cmp" : "Gerber Image" ,
".gbl" : "Gerber Image" ,
".gbo" : "Gerber Image" ,
".gbp" : "Gerber Image" ,
".gbs" : "Gerber Image" ,
".gko" : "Gerber Image" ,
".gml" : "Gerber Image" ,
".gpb" : "Gerber Image" ,
".gpt" : "Gerber Image" ,
".gtl" : "Gerber Image" ,
".gto" : "Gerber Image" ,
".gtp" : "Gerber Image" ,
".gts" : "Gerber Image" ,
".ncl" : "Gerber Image" ,
".sol" : "Gerber Image" ,
".po" : "Gettext Catalog" ,
".pot" : "Gettext Catalog" ,
".feature" : "Gherkin" ,
".story" : "Gherkin" ,
".gitconfig" : "Git Config" ,
".gleam" : "Gleam" ,
".gjs" : "Glimmer JS" ,
".glf" : "Glyph" ,
".bdf" : "Glyph Bitmap Distribution Format" ,
".gp" : "Gnuplot" ,
".gnu" : "Gnuplot" ,
".gnuplot" : "Gnuplot" ,
".p" : "Gnuplot" ,
".plot" : "Gnuplot" ,
".plt" : "Gnuplot" ,
".go" : "Go" ,
".gdnlib" : "Godot Resource" ,
".gdns" : "Godot Resource" ,
".tres" : "Godot Resource" ,
".tscn" : "Godot Resource" ,
".golo" : "Golo" ,
".gs" : "Gosu" ,
".gst" : "Gosu" ,
".gsx" : "Gosu" ,
".vark" : "Gosu" ,
".grace" : "Grace" ,
".gradle" : "Gradle" ,
".gradle.kts" : "Gradle Kotlin DSL" ,
".gf" : "Grammatical Framework" ,
".gml" : "Graph Modeling Language" ,
".graphql" : "GraphQL" ,
".gql" : "GraphQL" ,
".graphqls" : "GraphQL" ,
".dot" : "Graphviz (DOT)" ,
".gv" : "Graphviz (DOT)" ,
".groovy" : "Groovy" ,
".grt" : "Groovy" ,
".gtpl" : "Groovy" ,
".gvy" : "Groovy" ,
".gsp" : "Groovy Server Pages" ,
".cfg" : "HAProxy" ,
".hcl" : "HCL" ,
".nomad" : "HCL" ,
".tf" : "HCL" ,
".tfvars" : "HCL" ,
".workflow" : "HCL" ,
".hlsl" : "HLSL" ,
".cginc" : "HLSL" ,
".fx" : "HLSL" ,
".fxh" : "HLSL" ,
".hlsli" : "HLSL" ,
".hocon" : "HOCON" ,
".html" : "HTML" ,
".hta" : "HTML" ,
".htm" : "HTML" ,
".html.hl" : "HTML" ,
".inc" : "HTML" ,
".xht" : "HTML" ,
".xhtml" : "HTML" ,
".ecr" : "HTML+ECR" ,
".eex" : "HTML+EEX" ,
".html.heex" : "HTML+EEX" ,
".html.leex" : "HTML+EEX" ,
".erb" : "HTML+ERB" ,
".erb.deface" : "HTML+ERB" ,
".rhtml" : "HTML+ERB" ,
".phtml" : "HTML+PHP" ,
".cshtml" : "HTML+Razor" ,
".razor" : "HTML+Razor" ,
".http" : "HTTP" ,
".hxml" : "HXML" ,
".hack" : "Hack" ,
".hh" : "Hack" ,
".hhi" : "Hack" ,
".php" : "Hack" ,
".haml" : "Haml" ,
".haml.deface" : "Haml" ,
".handlebars" : "Handlebars" ,
".hbs" : "Handlebars" ,
".hb" : "Harbour" ,
".hs" : "Haskell" ,
".hs-boot" : "Haskell" ,
".hsc" : "Haskell" ,
".hx" : "Haxe" ,
".hxsl" : "Haxe" ,
".q" : "HiveQL" ,
".hql" : "HiveQL" ,
".hc" : "HolyC" ,
".hy" : "Hy" ,
".bf" : "HyPhy" ,
".pro" : "IDL" ,
".dlm" : "IDL" ,
".ipf" : "IGOR Pro" ,
".ini" : "INI" ,
".cfg" : "INI" ,
".cnf" : "INI" ,
".dof" : "INI" ,
".lektorproject" : "INI" ,
".prefs" : "INI" ,
".pro" : "INI" ,
".properties" : "INI" ,
".url" : "INI" ,
".irclog" : "IRC log" ,
".weechatlog" : "IRC log" ,
".idr" : "Idris" ,
".lidr" : "Idris" ,
".gitignore" : "Ignore List" ,
".ijm" : "ImageJ Macro" ,
".imba" : "Imba" ,
".ni" : "Inform 7" ,
".i7x" : "Inform 7" ,
".ink" : "Ink" ,
".iss" : "Inno Setup" ,
".isl" : "Inno Setup" ,
".io" : "Io" ,
".ik" : "Ioke" ,
".thy" : "Isabelle" ,
".ijs" : "J" ,
".jcl" : "JCL" ,
".flex" : "JFlex" ,
".jflex" : "JFlex" ,
".json" : "JSON" ,
".4DForm" : "JSON" ,
".4DProject" : "JSON" ,
".avsc" : "JSON" ,
".geojson" : "JSON" ,
".gltf" : "JSON" ,
".har" : "JSON" ,
".ice" : "JSON" ,
".JSON-tmLanguage" : "JSON" ,
".jsonl" : "JSON" ,
".mcmeta" : "JSON" ,
".tfstate" : "JSON" ,
".tfstate.backup" : "JSON" ,
".topojson" : "JSON" ,
".webapp" : "JSON" ,
".webmanifest" : "JSON" ,
".yy" : "JSON" ,
".yyp" : "JSON" ,
".jsonc" : "JSON with Comments" ,
".code-snippets" : "JSON with Comments" ,
".code-workspace" : "JSON with Comments" ,
".sublime-build" : "JSON with Comments" ,
".sublime-commands" : "JSON with Comments" ,
".sublime-completions" : "JSON with Comments" ,
".sublime-keymap" : "JSON with Comments" ,
".sublime-macro" : "JSON with Comments" ,
".sublime-menu" : "JSON with Comments" ,
".sublime-mousemap" : "JSON with Comments" ,
".sublime-project" : "JSON with Comments" ,
".sublime-settings" : "JSON with Comments" ,
".sublime-theme" : "JSON with Comments" ,
".sublime-workspace" : "JSON with Comments" ,
".sublime_metrics" : "JSON with Comments" ,
".sublime_session" : "JSON with Comments" ,
".json5" : "JSON5" ,
".jsonld" : "JSONLD" ,
".jq" : "JSONiq" ,
".janet" : "Janet" ,
".j" : "Jasmin" ,
".java" : "Java" ,
".jav" : "Java" ,
".jsh" : "Java" ,
".properties" : "Java Properties" ,
".jsp" : "Java Server Pages" ,
".tag" : "Java Server Pages" ,
".js" : "JavaScript" ,
"._js" : "JavaScript" ,
".bones" : "JavaScript" ,
".cjs" : "JavaScript" ,
".es" : "JavaScript" ,
".es6" : "JavaScript" ,
".frag" : "JavaScript" ,
".gs" : "JavaScript" ,
".jake" : "JavaScript" ,
".javascript" : "JavaScript" ,
".jsb" : "JavaScript" ,
".jscad" : "JavaScript" ,
".jsfl" : "JavaScript" ,
".jslib" : "JavaScript" ,
".jsm" : "JavaScript" ,
".jspre" : "JavaScript" ,
".jss" : "JavaScript" ,
".jsx" : "JavaScript" ,
".mjs" : "JavaScript" ,
".njs" : "JavaScript" ,
".pac" : "JavaScript" ,
".sjs" : "JavaScript" ,
".ssjs" : "JavaScript" ,
".xsjs" : "JavaScript" ,
".xsjslib" : "JavaScript" ,
".js.erb" : "JavaScript+ERB" ,
".snap" : "Jest Snapshot" ,
".mps" : "JetBrains MPS" ,
".mpl" : "JetBrains MPS" ,
".msd" : "JetBrains MPS" ,
".jinja" : "Jinja" ,
".j2" : "Jinja" ,
".jinja2" : "Jinja" ,
".jison" : "Jison" ,
".jisonlex" : "Jison Lex" ,
".ol" : "Jolie" ,
".iol" : "Jolie" ,
".jsonnet" : "Jsonnet" ,
".libsonnet" : "Jsonnet" ,
".jl" : "Julia" ,
".ipynb" : "Jupyter Notebook" ,
".krl" : "KRL" ,
".ksy" : "Kaitai Struct" ,
".kak" : "KakouneScript" ,
".ks" : "KerboScript" ,
".kicad_pcb" : "KiCad Layout" ,
".kicad_mod" : "KiCad Layout" ,
".kicad_wks" : "KiCad Layout" ,
".brd" : "KiCad Legacy Layout" ,
".kicad_sch" : "KiCad Schematic" ,
".sch" : "KiCad Schematic" ,
".ks" : "Kickstart" ,
".kit" : "Kit" ,
".kt" : "Kotlin" ,
".ktm" : "Kotlin" ,
".kts" : "Kotlin" ,
".csl" : "Kusto" ,
".kql" : "Kusto" ,
".lfe" : "LFE" ,
".ll" : "LLVM" ,
".lol" : "LOLCODE" ,
".lsl" : "LSL" ,
".lslp" : "LSL" ,
".asy" : "LTspice Symbol" ,
".lvproj" : "LabVIEW" ,
".lvclass" : "LabVIEW" ,
".lvlib" : "LabVIEW" ,
".lark" : "Lark" ,
".lasso" : "Lasso" ,
".las" : "Lasso" ,
".lasso8" : "Lasso" ,
".lasso9" : "Lasso" ,
".latte" : "Latte" ,
".lean" : "Lean" ,
".hlean" : "Lean" ,
".lean" : "Lean 4" ,
".less" : "Less" ,
".l" : "Lex" ,
".lex" : "Lex" ,
".ligo" : "LigoLANG" ,
".ly" : "LilyPond" ,
".ily" : "LilyPond" ,
".b" : "Limbo" ,
".m" : "Limbo" ,
".ld" : "Linker Script" ,
".lds" : "Linker Script" ,
".x" : "Linker Script" ,
".mod" : "Linux Kernel Module" ,
".liquid" : "Liquid" ,
".lagda" : "Literate Agda" ,
".litcoffee" : "Literate CoffeeScript" ,
".coffee.md" : "Literate CoffeeScript" ,
".lhs" : "Literate Haskell" ,
".ls" : "LiveScript" ,
"._ls" : "LiveScript" ,
".xm" : "Logos" ,
".x" : "Logos" ,
".xi" : "Logos" ,
".lgt" : "Logtalk" ,
".logtalk" : "Logtalk" ,
".lkml" : "LookML" ,
".lookml" : "LookML" ,
".ls" : "LoomScript" ,
".lua" : "Lua" ,
".fcgi" : "Lua" ,
".nse" : "Lua" ,
".p8" : "Lua" ,
".pd_lua" : "Lua" ,
".rbxs" : "Lua" ,
".rockspec" : "Lua" ,
".wlua" : "Lua" ,
".mumps" : "M" ,
".m" : "M" ,
".m4" : "M4" ,
".mc" : "M4" ,
".m4" : "M4Sugar" ,
".matlab" : "MATLAB" ,
".m" : "MATLAB" ,
".ms" : "MAXScript" ,
".mcr" : "MAXScript" ,
".mdx" : "MDX" ,
".mlir" : "MLIR" ,
".mq4" : "MQL4" ,
".mqh" : "MQL4" ,
".mq5" : "MQL5" ,
".mqh" : "MQL5" ,
".mtml" : "MTML" ,
".muf" : "MUF" ,
".m" : "MUF" ,
".m2" : "Macaulay2" ,
".mak" : "Makefile" ,
".d" : "Makefile" ,
".make" : "Makefile" ,
".makefile" : "Makefile" ,
".mk" : "Makefile" ,
".mkfile" : "Makefile" ,
".mako" : "Mako" ,
".mao" : "Mako" ,
".md" : "Markdown" ,
".livemd" : "Markdown" ,
".markdown" : "Markdown" ,
".mdown" : "Markdown" ,
".mdwn" : "Markdown" ,
".mkd" : "Markdown" ,
".mkdn" : "Markdown" ,
".mkdown" : "Markdown" ,
".ronn" : "Markdown" ,
".scd" : "Markdown" ,
".workbook" : "Markdown" ,
".marko" : "Marko" ,
".mask" : "Mask" ,
".mathematica" : "Mathematica" ,
".cdf" : "Mathematica" ,
".m" : "Mathematica" ,
".ma" : "Mathematica" ,
".mt" : "Mathematica" ,
".nb" : "Mathematica" ,
".nbp" : "Mathematica" ,
".wl" : "Mathematica" ,
".wlt" : "Mathematica" ,
".maxpat" : "Max" ,
".maxhelp" : "Max" ,
".maxproj" : "Max" ,
".mxt" : "Max" ,
".pat" : "Max" ,
".m" : "Mercury" ,
".moo" : "Mercury" ,
".mmd" : "Mermaid" ,
".mermaid" : "Mermaid" ,
".metal" : "Metal" ,
".dsp" : "Microsoft Developer Studio Project" ,
".sln" : "Microsoft Visual Studio Solution" ,
".minid" : "MiniD" ,
".yaml" : "MiniYAML" ,
".yml" : "MiniYAML" ,
".mint" : "Mint" ,
".druby" : "Mirah" ,
".duby" : "Mirah" ,
".mirah" : "Mirah" ,
".mo" : "Modelica" ,
".mod" : "Modula-2" ,
".i3" : "Modula-3" ,
".ig" : "Modula-3" ,
".m3" : "Modula-3" ,
".mg" : "Modula-3" ,
".mms" : "Module Management System" ,
".mmk" : "Module Management System" ,
".monkey" : "Monkey" ,
".monkey2" : "Monkey" ,
".mc" : "Monkey C" ,
".moo" : "Moocode" ,
".moon" : "MoonScript" ,
".mo" : "Motoko" ,
".asm" : "Motorola 68K Assembly" ,
".i" : "Motorola 68K Assembly" ,
".inc" : "Motorola 68K Assembly" ,
".s" : "Motorola 68K Assembly" ,
".x68" : "Motorola 68K Assembly" ,
".move" : "Move" ,
".muse" : "Muse" ,
".mustache" : "Mustache" ,
".myt" : "Myghty" ,
".nasl" : "NASL" ,
".inc" : "NASL" ,
".ncl" : "NCL" ,
".neon" : "NEON" ,
".nl" : "NL" ,
".nsi" : "NSIS" ,
".nsh" : "NSIS" ,
".nss" : "NWScript" ,
".nas" : "Nasal" ,
".ne" : "Nearley" ,
".nearley" : "Nearley" ,
".n" : "Nemerle" ,
".axs" : "NetLinx" ,
".axi" : "NetLinx" ,
".axs.erb" : "NetLinx+ERB" ,
".axi.erb" : "NetLinx+ERB" ,
".nlogo" : "NetLogo" ,
".nl" : "NewLisp" ,
".lisp" : "NewLisp" ,
".lsp" : "NewLisp" ,
".nf" : "Nextflow" ,
".nginx" : "Nginx" ,
".nginxconf" : "Nginx" ,
".vhost" : "Nginx" ,
".nim" : "Nim" ,
".nim.cfg" : "Nim" ,
".nimble" : "Nim" ,
".nimrod" : "Nim" ,
".nims" : "Nim" ,
".ninja" : "Ninja" ,
".nit" : "Nit" ,
".nix" : "Nix" ,
".nu" : "Nu" ,
".numpy" : "NumPy" ,
".numpyw" : "NumPy" ,
".numsc" : "NumPy" ,
".njk" : "Nunjucks" ,
".nu" : "Nushell" ,
".json" : "OASv2-json" ,
".yaml" : "OASv2-yaml" ,
".yml" : "OASv2-yaml" ,
".json" : "OASv3-json" ,
".yaml" : "OASv3-yaml" ,
".yml" : "OASv3-yaml" ,
".ml" : "OCaml" ,
".eliom" : "OCaml" ,
".eliomi" : "OCaml" ,
".ml4" : "OCaml" ,
".mli" : "OCaml" ,
".mll" : "OCaml" ,
".mly" : "OCaml" ,
".objdump" : "ObjDump" ,
".odin" : "Object Data Instance Notation" ,
".cls" : "ObjectScript" ,
".m" : "Objective-C" ,
".h" : "Objective-C" ,
".mm" : "Objective-C++" ,
".j" : "Objective-J" ,
".sj" : "Objective-J" ,
".odin" : "Odin" ,
".omgrofl" : "Omgrofl" ,
".opa" : "Opa" ,
".opal" : "Opal" ,
".rego" : "Open Policy Agent" ,
".cl" : "OpenCL" ,
".opencl" : "OpenCL" ,
".p" : "OpenEdge ABL" ,
".cls" : "OpenEdge ABL" ,
".w" : "OpenEdge ABL" ,
".qasm" : "OpenQASM" ,
".scad" : "OpenSCAD" ,
".plist" : "OpenStep Property List" ,
".glyphs" : "OpenStep Property List" ,
".fea" : "OpenType Feature File" ,
".org" : "Org" ,
".ox" : "Ox" ,
".oxh" : "Ox" ,
".oxo" : "Ox" ,
".oxygene" : "Oxygene" ,
".oz" : "Oz" ,
".p4" : "P4" ,
".pddl" : "PDDL" ,
".pegjs" : "PEG.js" ,
".php" : "PHP" ,
".aw" : "PHP" ,
".ctp" : "PHP" ,
".fcgi" : "PHP" ,
".inc" : "PHP" ,
".php3" : "PHP" ,
".php4" : "PHP" ,
".php5" : "PHP" ,
".phps" : "PHP" ,
".phpt" : "PHP" ,
".pls" : "PLSQL" ,
".bdy" : "PLSQL" ,
".ddl" : "PLSQL" ,
".fnc" : "PLSQL" ,
".pck" : "PLSQL" ,
".pkb" : "PLSQL" ,
".pks" : "PLSQL" ,
".plb" : "PLSQL" ,
".plsql" : "PLSQL" ,
".prc" : "PLSQL" ,
".spc" : "PLSQL" ,
".sql" : "PLSQL" ,
".tpb" : "PLSQL" ,
".tps" : "PLSQL" ,
".trg" : "PLSQL" ,
".vw" : "PLSQL" ,
".pgsql" : "PLpgSQL" ,
".sql" : "PLpgSQL" ,
".pov" : "POV-Ray SDL" ,
".inc" : "POV-Ray SDL" ,
".pact" : "Pact" ,
".pan" : "Pan" ,
".psc" : "Papyrus" ,
".parrot" : "Parrot" ,
".pasm" : "Parrot Assembly" ,
".pir" : "Parrot Internal Representation" ,
".pas" : "Pascal" ,
".dfm" : "Pascal" ,
".dpr" : "Pascal" ,
".inc" : "Pascal" ,
".lpr" : "Pascal" ,
".pascal" : "Pascal" ,
".pp" : "Pascal" ,
".pwn" : "Pawn" ,
".inc" : "Pawn" ,
".sma" : "Pawn" ,
".pep" : "Pep8" ,
".pl" : "Perl" ,
".al" : "Perl" ,
".cgi" : "Perl" ,
".fcgi" : "Perl" ,
".perl" : "Perl" ,
".ph" : "Perl" ,
".plx" : "Perl" ,
".pm" : "Perl" ,
".psgi" : "Perl" ,
".t" : "Perl" ,
".pic" : "Pic" ,
".chem" : "Pic" ,
".pkl" : "Pickle" ,
".l" : "PicoLisp" ,
".pig" : "PigLatin" ,
".pike" : "Pike" ,
".pmod" : "Pike" ,
".puml" : "PlantUML" ,
".iuml" : "PlantUML" ,
".plantuml" : "PlantUML" ,
".pod" : "Pod" ,
".pod" : "Pod 6" ,
".pod6" : "Pod 6" ,
".pogo" : "PogoScript" ,
".polar" : "Polar" ,
".pony" : "Pony" ,
".por" : "Portugol" ,
".pcss" : "PostCSS" ,
".postcss" : "PostCSS" ,
".ps" : "PostScript" ,
".eps" : "PostScript" ,
".epsi" : "PostScript" ,
".pfa" : "PostScript" ,
".pbt" : "PowerBuilder" ,
".sra" : "PowerBuilder" ,
".sru" : "PowerBuilder" ,
".srw" : "PowerBuilder" ,
".ps1" : "PowerShell" ,
".psd1" : "PowerShell" ,
".psm1" : "PowerShell" ,
".praat" : "Praat" ,
".prisma" : "Prisma" ,
".pde" : "Processing" ,
".pro" : "Proguard" ,
".pl" : "Prolog" ,
".plt" : "Prolog" ,
".pro" : "Prolog" ,
".prolog" : "Prolog" ,
".yap" : "Prolog" ,
".pml" : "Promela" ,
".spin" : "Propeller Spin" ,
".proto" : "Protocol Buffer" ,
".textproto" : "Protocol Buffer Text Format" ,
".pbt" : "Protocol Buffer Text Format" ,
".pbtxt" : "Protocol Buffer Text Format" ,
".asc" : "Public Key" ,
".pub" : "Public Key" ,
".jade" : "Pug" ,
".pug" : "Pug" ,
".pp" : "Puppet" ,
".pd" : "Pure Data" ,
".pb" : "PureBasic" ,
".pbi" : "PureBasic" ,
".purs" : "PureScript" ,
".arr" : "Pyret" ,
".py" : "Python" ,
".cgi" : "Python" ,
".fcgi" : "Python" ,
".gyp" : "Python" ,
".gypi" : "Python" ,
".lmi" : "Python" ,
".py3" : "Python" ,
".pyde" : "Python" ,
".pyi" : "Python" ,
".pyp" : "Python" ,
".pyt" : "Python" ,
".pyw" : "Python" ,
".rpy" : "Python" ,
".spec" : "Python" ,
".tac" : "Python" ,
".wsgi" : "Python" ,
".xpy" : "Python" ,
".pytb" : "Python traceback" ,
".qs" : "Q#" ,
".qml" : "QML" ,
".qbs" : "QML" ,
".pro" : "QMake" ,
".pri" : "QMake" ,
".qs" : "Qt Script" ,
".r" : "R" ,
".rd" : "R" ,
".rsx" : "R" ,
".raml" : "RAML" ,
".rbs" : "RBS" ,
".rdoc" : "RDoc" ,
".rbbas" : "REALbasic" ,
".rbfrm" : "REALbasic" ,
".rbmnu" : "REALbasic" ,
".rbres" : "REALbasic" ,
".rbtbar" : "REALbasic" ,
".rbuistate" : "REALbasic" ,
".rexx" : "REXX" ,
".pprx" : "REXX" ,
".rex" : "REXX" ,
".qmd" : "RMarkdown" ,
".rmd" : "RMarkdown" ,
".x" : "RPC" ,
".rpgle" : "RPGLE" ,
".sqlrpgle" : "RPGLE" ,
".spec" : "RPM Spec" ,
".rnh" : "RUNOFF" ,
".rno" : "RUNOFF" ,
".rkt" : "Racket" ,
".rktd" : "Racket" ,
".rktl" : "Racket" ,
".scrbl" : "Racket" ,
".rl" : "Ragel" ,
".6pl" : "Raku" ,
".6pm" : "Raku" ,
".nqp" : "Raku" ,
".p6" : "Raku" ,
".p6l" : "Raku" ,
".p6m" : "Raku" ,
".pl" : "Raku" ,
".pl6" : "Raku" ,
".pm" : "Raku" ,
".pm6" : "Raku" ,
".raku" : "Raku" ,
".rakumod" : "Raku" ,
".t" : "Raku" ,
".rsc" : "Rascal" ,
".raw" : "Raw token data" ,
".res" : "ReScript" ,
".re" : "Reason" ,
".rei" : "Reason" ,
".religo" : "ReasonLIGO" ,
".reb" : "Rebol" ,
".r" : "Rebol" ,
".r2" : "Rebol" ,
".r3" : "Rebol" ,
".rebol" : "Rebol" ,
".red" : "Red" ,
".reds" : "Red" ,
".cw" : "Redcode" ,
".regexp" : "Regular Expression" ,
".regex" : "Regular Expression" ,
".rpy" : "Ren'Py" ,
".rs" : "RenderScript" ,
".rsh" : "RenderScript" ,
".r" : "Rez" ,
".rtf" : "Rich Text Format" ,
".ring" : "Ring" ,
".riot" : "Riot" ,
".robot" : "RobotFramework" ,
".roff" : "Roff" ,
".1" : "Roff" ,
".1in" : "Roff" ,
".1m" : "Roff" ,
".1x" : "Roff" ,
".2" : "Roff" ,
".3" : "Roff" ,
".3in" : "Roff" ,
".3m" : "Roff" ,
".3p" : "Roff" ,
".3pm" : "Roff" ,
".3qt" : "Roff" ,
".3x" : "Roff" ,
".4" : "Roff" ,
".5" : "Roff" ,
".6" : "Roff" ,
".7" : "Roff" ,
".8" : "Roff" ,
".9" : "Roff" ,
".l" : "Roff" ,
".man" : "Roff" ,
".mdoc" : "Roff" ,
".me" : "Roff" ,
".ms" : "Roff" ,
".n" : "Roff" ,
".nr" : "Roff" ,
".rno" : "Roff" ,
".tmac" : "Roff" ,
".1" : "Roff Manpage" ,
".1in" : "Roff Manpage" ,
".1m" : "Roff Manpage" ,
".1x" : "Roff Manpage" ,
".2" : "Roff Manpage" ,
".3" : "Roff Manpage" ,
".3in" : "Roff Manpage" ,
".3m" : "Roff Manpage" ,
".3p" : "Roff Manpage" ,
".3pm" : "Roff Manpage" ,
".3qt" : "Roff Manpage" ,
".3x" : "Roff Manpage" ,
".4" : "Roff Manpage" ,
".5" : "Roff Manpage" ,
".6" : "Roff Manpage" ,
".7" : "Roff Manpage" ,
".8" : "Roff Manpage" ,
".9" : "Roff Manpage" ,
".man" : "Roff Manpage" ,
".mdoc" : "Roff Manpage" ,
".rg" : "Rouge" ,
".rsc" : "RouterOS Script" ,
".rb" : "Ruby" ,
".builder" : "Ruby" ,
".eye" : "Ruby" ,
".fcgi" : "Ruby" ,
".gemspec" : "Ruby" ,
".god" : "Ruby" ,
".jbuilder" : "Ruby" ,
".mspec" : "Ruby" ,
".pluginspec" : "Ruby" ,
".podspec" : "Ruby" ,
".prawn" : "Ruby" ,
".rabl" : "Ruby" ,
".rake" : "Ruby" ,
".rbi" : "Ruby" ,
".rbuild" : "Ruby" ,
".rbw" : "Ruby" ,
".rbx" : "Ruby" ,
".ru" : "Ruby" ,
".ruby" : "Ruby" ,
".spec" : "Ruby" ,
".thor" : "Ruby" ,
".watchr" : "Ruby" ,
".rs" : "Rust" ,
".rs.in" : "Rust" ,
".sas" : "SAS" ,
".scss" : "SCSS" ,
".te" : "SELinux Policy" ,
".smt2" : "SMT" ,
".smt" : "SMT" ,
".sparql" : "SPARQL" ,
".rq" : "SPARQL" ,
".sqf" : "SQF" ,
".hqf" : "SQF" ,
".sql" : "SQL" ,
".cql" : "SQL" ,
".ddl" : "SQL" ,
".inc" : "SQL" ,
".mysql" : "SQL" ,
".prc" : "SQL" ,
".tab" : "SQL" ,
".udf" : "SQL" ,
".viw" : "SQL" ,
".sql" : "SQLPL" ,
".db2" : "SQLPL" ,
".srt" : "SRecode Template" ,
".star" : "STAR" ,
".stl" : "STL" ,
".ston" : "STON" ,
".svg" : "SVG" ,
".i" : "SWIG" ,
".sage" : "Sage" ,
".sagews" : "Sage" ,
".sls" : "SaltStack" ,
".sass" : "Sass" ,
".scala" : "Scala" ,
".kojo" : "Scala" ,
".sbt" : "Scala" ,
".sc" : "Scala" ,
".scaml" : "Scaml" ,
".scenic" : "Scenic" ,
".scm" : "Scheme" ,
".sch" : "Scheme" ,
".sld" : "Scheme" ,
".sls" : "Scheme" ,
".sps" : "Scheme" ,
".ss" : "Scheme" ,
".sci" : "Scilab" ,
".sce" : "Scilab" ,
".tst" : "Scilab" ,
".self" : "Self" ,
".shader" : "ShaderLab" ,
".sh" : "Shell" ,
".bash" : "Shell" ,
".bats" : "Shell" ,
".cgi" : "Shell" ,
".command" : "Shell" ,
".fcgi" : "Shell" ,
".ksh" : "Shell" ,
".sh.in" : "Shell" ,
".tmux" : "Shell" ,
".tool" : "Shell" ,
".trigger" : "Shell" ,
".zsh" : "Shell" ,
".zsh-theme" : "Shell" ,
".sh-session" : "ShellSession" ,
".shen" : "Shen" ,
".sieve" : "Sieve" ,
".sfv" : "Simple File Verification" ,
".sl" : "Slash" ,
".ice" : "Slice" ,
".slim" : "Slim" ,
".cocci" : "SmPL" ,
".smali" : "Smali" ,
".st" : "Smalltalk" ,
".cs" : "Smalltalk" ,
".tpl" : "Smarty" ,
".smithy" : "Smithy" ,
".smk" : "Snakemake" ,
".snakefile" : "Snakemake" ,
".sol" : "Solidity" ,
".sp" : "SourcePawn" ,
".inc" : "SourcePawn" ,
".sfd" : "Spline Font Database" ,
".nut" : "Squirrel" ,
".stan" : "Stan" ,
".ml" : "Standard ML" ,
".fun" : "Standard ML" ,
".sig" : "Standard ML" ,
".sml" : "Standard ML" ,
".bzl" : "Starlark" ,
".star" : "Starlark" ,
".do" : "Stata" ,
".ado" : "Stata" ,
".doh" : "Stata" ,
".ihlp" : "Stata" ,
".mata" : "Stata" ,
".matah" : "Stata" ,
".sthlp" : "Stata" ,
".st" : "StringTemplate" ,
".styl" : "Stylus" ,
".srt" : "SubRip Text" ,
".sss" : "SugarSS" ,
".sc" : "SuperCollider" ,
".scd" : "SuperCollider" ,
".svelte" : "Svelte" ,
".sw" : "Sway" ,
".rnw" : "Sweave" ,
".swift" : "Swift" ,
".sv" : "SystemVerilog" ,
".svh" : "SystemVerilog" ,
".vh" : "SystemVerilog" ,
".8xp" : "TI Program" ,
".8xk" : "TI Program" ,
".8xk.txt" : "TI Program" ,
".8xp.txt" : "TI Program" ,
".tlv" : "TL-Verilog" ,
".tla" : "TLA" ,
".toml" : "TOML" ,
".sql" : "TSQL" ,
".tsv" : "TSV" ,
".tsx" : "TSX" ,
".txl" : "TXL" ,
".talon" : "Talon" ,
".tcl" : "Tcl" ,
".adp" : "Tcl" ,
".sdc" : "Tcl" ,
".tcl.in" : "Tcl" ,
".tm" : "Tcl" ,
".xdc" : "Tcl" ,
".tcsh" : "Tcsh" ,
".csh" : "Tcsh" ,
".tex" : "TeX" ,
".aux" : "TeX" ,
".bbx" : "TeX" ,
".cbx" : "TeX" ,
".cls" : "TeX" ,
".dtx" : "TeX" ,
".ins" : "TeX" ,
".lbx" : "TeX" ,
".ltx" : "TeX" ,
".mkii" : "TeX" ,
".mkiv" : "TeX" ,
".mkvi" : "TeX" ,
".sty" : "TeX" ,
".toc" : "TeX" ,
".tea" : "Tea" ,
".t" : "Terra" ,
".tftpl" : "Terraform Template" ,
".texinfo" : "Texinfo" ,
".texi" : "Texinfo" ,
".txi" : "Texinfo" ,
".txt" : "Text" ,
".fr" : "Text" ,
".nb" : "Text" ,
".ncl" : "Text" ,
".no" : "Text" ,
".textile" : "Textile" ,
".thrift" : "Thrift" ,
".toit" : "Toit" ,
".t" : "Turing" ,
".tu" : "Turing" ,
".ttl" : "Turtle" ,
".twig" : "Twig" ,
".tl" : "Type Language" ,
".ts" : "TypeScript" ,
".cts" : "TypeScript" ,
".mts" : "TypeScript" ,
".typ" : "Typst" ,
".upc" : "Unified Parallel C" ,
".anim" : "Unity3D Asset" ,
".asset" : "Unity3D Asset" ,
".mask" : "Unity3D Asset" ,
".mat" : "Unity3D Asset" ,
".meta" : "Unity3D Asset" ,
".prefab" : "Unity3D Asset" ,
".unity" : "Unity3D Asset" ,
".s" : "Unix Assembly" ,
".ms" : "Unix Assembly" ,
".uno" : "Uno" ,
".uc" : "UnrealScript" ,
".ur" : "UrWeb" ,
".urs" : "UrWeb" ,
".v" : "V" ,
".bas" : "VBA" ,
".cls" : "VBA" ,
".frm" : "VBA" ,
".vba" : "VBA" ,
".vbs" : "VBScript" ,
".vcl" : "VCL" ,
".vhdl" : "VHDL" ,
".vhd" : "VHDL" ,
".vhf" : "VHDL" ,
".vhi" : "VHDL" ,
".vho" : "VHDL" ,
".vhs" : "VHDL" ,
".vht" : "VHDL" ,
".vhw" : "VHDL" ,
".vala" : "Vala" ,
".vapi" : "Vala" ,
".vdf" : "Valve Data Format" ,
".vtl" : "Velocity Template Language" ,
".v" : "Verilog" ,
".veo" : "Verilog" ,
".txt" : "Vim Help File" ,
".vim" : "Vim Script" ,
".vba" : "Vim Script" ,
".vimrc" : "Vim Script" ,
".vmb" : "Vim Script" ,
".snip" : "Vim Snippet" ,
".snippet" : "Vim Snippet" ,
".snippets" : "Vim Snippet" ,
".vb" : "Visual Basic .NET" ,
".vbhtml" : "Visual Basic .NET" ,
".bas" : "Visual Basic 6.0" ,
".cls" : "Visual Basic 6.0" ,
".ctl" : "Visual Basic 6.0" ,
".Dsr" : "Visual Basic 6.0" ,
".frm" : "Visual Basic 6.0" ,
".volt" : "Volt" ,
".vue" : "Vue" ,
".vy" : "Vyper" ,
".wdl" : "WDL" ,
".wgsl" : "WGSL" ,
".mtl" : "Wavefront Material" ,
".obj" : "Wavefront Object" ,
".owl" : "Web Ontology Language" ,
".wast" : "WebAssembly" ,
".wat" : "WebAssembly" ,
".wit" : "WebAssembly Interface Type" ,
".webidl" : "WebIDL" ,
".vtt" : "WebVTT" ,
".whiley" : "Whiley" ,
".mediawiki" : "Wikitext" ,
".wiki" : "Wikitext" ,
".wikitext" : "Wikitext" ,
".mc" : "Win32 Message File" ,
".reg" : "Windows Registry Entries" ,
".ws" : "Witcher Script" ,
".wlk" : "Wollok" ,
".toc" : "World of Warcraft Addon Data" ,
".wren" : "Wren" ,
".xbm" : "X BitMap" ,
".xpm" : "X PixMap" ,
".pm" : "X PixMap" ,
".x10" : "X10" ,
".xc" : "XC" ,
".xml" : "XML" ,
".adml" : "XML" ,
".admx" : "XML" ,
".ant" : "XML" ,
".axaml" : "XML" ,
".axml" : "XML" ,
".builds" : "XML" ,
".ccproj" : "XML" ,
".ccxml" : "XML" ,
".clixml" : "XML" ,
".cproject" : "XML" ,
".cscfg" : "XML" ,
".csdef" : "XML" ,
".csl" : "XML" ,
".csproj" : "XML" ,
".ct" : "XML" ,
".depproj" : "XML" ,
".dita" : "XML" ,
".ditamap" : "XML" ,
".ditaval" : "XML" ,
".dll.config" : "XML" ,
".dotsettings" : "XML" ,
".filters" : "XML" ,
".fsproj" : "XML" ,
".fxml" : "XML" ,
".glade" : "XML" ,
".gml" : "XML" ,
".gmx" : "XML" ,
".grxml" : "XML" ,
".gst" : "XML" ,
".hzp" : "XML" ,
".iml" : "XML" ,
".ivy" : "XML" ,
".jelly" : "XML" ,
".jsproj" : "XML" ,
".kml" : "XML" ,
".launch" : "XML" ,
".mdpolicy" : "XML" ,
".mjml" : "XML" ,
".mm" : "XML" ,
".mod" : "XML" ,
".mxml" : "XML" ,
".natvis" : "XML" ,
".ncl" : "XML" ,
".ndproj" : "XML" ,
".nproj" : "XML" ,
".nuspec" : "XML" ,
".odd" : "XML" ,
".osm" : "XML" ,
".pkgproj" : "XML" ,
".pluginspec" : "XML" ,
".proj" : "XML" ,
".props" : "XML" ,
".ps1xml" : "XML" ,
".psc1" : "XML" ,
".pt" : "XML" ,
".qhelp" : "XML" ,
".rdf" : "XML" ,
".res" : "XML" ,
".resx" : "XML" ,
".rs" : "XML" ,
".rss" : "XML" ,
".sch" : "XML" ,
".scxml" : "XML" ,
".sfproj" : "XML" ,
".shproj" : "XML" ,
".srdf" : "XML" ,
".storyboard" : "XML" ,
".sublime-snippet" : "XML" ,
".sw" : "XML" ,
".targets" : "XML" ,
".tml" : "XML" ,
".ts" : "XML" ,
".tsx" : "XML" ,
".typ" : "XML" ,
".ui" : "XML" ,
".urdf" : "XML" ,
".ux" : "XML" ,
".vbproj" : "XML" ,
".vcxproj" : "XML" ,
".vsixmanifest" : "XML" ,
".vssettings" : "XML" ,
".vstemplate" : "XML" ,
".vxml" : "XML" ,
".wixproj" : "XML" ,
".workflow" : "XML" ,
".wsdl" : "XML" ,
".wsf" : "XML" ,
".wxi" : "XML" ,
".wxl" : "XML" ,
".wxs" : "XML" ,
".x3d" : "XML" ,
".xacro" : "XML" ,
".xaml" : "XML" ,
".xib" : "XML" ,
".xlf" : "XML" ,
".xliff" : "XML" ,
".xmi" : "XML" ,
".xml.dist" : "XML" ,
".xmp" : "XML" ,
".xproj" : "XML" ,
".xsd" : "XML" ,
".xspec" : "XML" ,
".xul" : "XML" ,
".zcml" : "XML" ,
".plist" : "XML Property List" ,
".stTheme" : "XML Property List" ,
".tmCommand" : "XML Property List" ,
".tmLanguage" : "XML Property List" ,
".tmPreferences" : "XML Property List" ,
".tmSnippet" : "XML Property List" ,
".tmTheme" : "XML Property List" ,
".xsp-config" : "XPages" ,
".xsp.metadata" : "XPages" ,
".xpl" : "XProc" ,
".xproc" : "XProc" ,
".xquery" : "XQuery" ,
".xq" : "XQuery" ,
".xql" : "XQuery" ,
".xqm" : "XQuery" ,
".xqy" : "XQuery" ,
".xs" : "XS" ,
".xslt" : "XSLT" ,
".xsl" : "XSLT" ,
".xojo_code" : "Xojo" ,
".xojo_menu" : "Xojo" ,
".xojo_report" : "Xojo" ,
".xojo_script" : "Xojo" ,
".xojo_toolbar" : "Xojo" ,
".xojo_window" : "Xojo" ,
".xsh" : "Xonsh" ,
".xtend" : "Xtend" ,
".yml" : "YAML" ,
".mir" : "YAML" ,
".reek" : "YAML" ,
".rviz" : "YAML" ,
".sublime-syntax" : "YAML" ,
".syntax" : "YAML" ,
".yaml" : "YAML" ,
".yaml-tmlanguage" : "YAML" ,
".yaml.sed" : "YAML" ,
".yml.mysql" : "YAML" ,
".yang" : "YANG" ,
".yar" : "YARA" ,
".yara" : "YARA" ,
".yasnippet" : "YASnippet" ,
".y" : "Yacc" ,
".yacc" : "Yacc" ,
".yy" : "Yacc" ,
".yul" : "Yul" ,
".zap" : "ZAP" ,
".xzap" : "ZAP" ,
".zil" : "ZIL" ,
".mud" : "ZIL" ,
".zeek" : "Zeek" ,
".bro" : "Zeek" ,
".zs" : "ZenScript" ,
".zep" : "Zephir" ,
".zig" : "Zig" ,
".zimpl" : "Zimpl" ,
".zmpl" : "Zimpl" ,
".zpl" : "Zimpl" ,
".desktop" : "desktop" ,
".desktop.in" : "desktop" ,
".service" : "desktop" ,
".dircolors" : "dircolors" ,
".ec" : "eC" ,
".eh" : "eC" ,
".edn" : "edn" ,
".fish" : "fish" ,
".hoon" : "hoon" ,
".jq" : "jq" ,
".kv" : "kvlang" ,
".mrc" : "mIRC Script" ,
".mcfunction" : "mcfunction" ,
".mu" : "mupad" ,
".nanorc" : "nanorc" ,
".nc" : "nesC" ,
".ooc" : "ooc" ,
".q" : "q" ,
".rst" : "reStructuredText" ,
".rest" : "reStructuredText" ,
".rest.txt" : "reStructuredText" ,
".rst.txt" : "reStructuredText" ,
".sed" : "sed" ,
".wisp" : "wisp" ,
".prg" : "xBase" ,
".ch" : "xBase" ,
".prw" : "xBase" 
}